export default {
  "data":[
  {
    "name":"中西药品",
    "id":"1",
    "parentId":"",
    "goods":[
      {
        "name":"感冒清热",
        "id":"2",
        "parentId":"1",
        "arr":[
          {
            "name":"感冒解表",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwB4OALPPIAACLpJ2unBk380.jpg",
            "id":"3",
            "parentId":"2"
          },
          {
            "name":"支气管炎/咳嗽",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwB7eAKJn8AACYowzFVq4756.jpg",
            "id":"4",
            "parentId":"2"
          },
          {
            "name":"解热镇痛",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwB-SAHRSVAAB3hlig6-Q130.jpg",
            "id":"5",
            "parentId":"2"
          },
          {
            "name":"清热解毒",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwCCaARyFPAABwWzJMOZ0363.jpg",
            "id":"6",
            "parentId":"2"
          },
          {
            "name":"咽喉炎",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwCFGAFRKdAABYLpkwNqI496.jpg",
            "id":"7",
            "parentId":"1"
          }
        ]
      },
      {
        "name":"微生物类",
        "id":"8",
        "parentId":"1",
        "arr":[
          {
            "id":"9",
            "parentId":"8",
            "name":"抗菌类",
            "img":"http://static.360hwj.com/group1/M00/00/AE/J2zAA1lgd6mAVB9DAABvQHdJlVk019.JPG"
          },
          {
            "id":"10",
            "parentId":"8",
            "name":"抗病毒类",
            "img":"http://static.360hwj.com/group1/M00/00/B1/J2zAA1lgeA6AcyeUAABUtQ9R-rk890.JPG"
          },
          {
            "id":"11",
            "parentId":"8",
            "name":"结核病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwFl2AdIYeAAByU7_adts548.jpg"
          }
        ]
      },
      {
        "id":"12",
        "parentId":"1",
        "name":"心脑血管",
        "arr":[
          {
            "id":"13",
            "name":"心绞痛",
            "img":"http://static.360hwj.com/group1/M00/01/F8/J2zAA1lwYXiAftXyAAFElVpO-LQ620.jpg"
          },
          {
            "id":"14",
            "name":"血压异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          },
          {
            "id":"15",
            "name":"血脂异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwGmmAGxluAABMsdGxEZk146.jpg"
          },
          {
            "id":"16",
            "name":"脑血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwFbGAe6jmAABxOpNd5dU469.jpg"
          },
          {
            "id":"17",
            "name":"心血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          }


        ]
      },
      {
        "id":"18",
        "name":"心脑血管",
        "arr":[
          {
            "id":"19",
            "name":"心绞痛",
            "img":"http://static.360hwj.com/group1/M00/01/F8/J2zAA1lwYXiAftXyAAFElVpO-LQ620.jpg"
          },
          {
            "id":"20",
            "name":"血压异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          },
          {
            "id":"21",
            "name":"血脂异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwGmmAGxluAABMsdGxEZk146.jpg"
          },
          {
            "id":"22",
            "name":"脑血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwFbGAe6jmAABxOpNd5dU469.jpg"
          },
          {
            "id":"23",
            "name":"心血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          }
        ]
      },
      {
        "id":"24",
        "name":"心脑血管",
        "arr":[
          {
            "id":"25",
            "name":"心绞痛",
            "img":"http://static.360hwj.com/group1/M00/01/F8/J2zAA1lwYXiAftXyAAFElVpO-LQ620.jpg"
          },
          {
            "id":"26",
            "name":"血压异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          },
          {
            "id":"27",
            "name":"血脂异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwGmmAGxluAABMsdGxEZk146.jpg"
          },
          {
            "id":"28",
            "name":"脑血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwFbGAe6jmAABxOpNd5dU469.jpg"
          },
          {
            "id":"29",
            "name":"心血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          }
        ]
      }
    ]
  },
  {
    "id":"30",
    "name":"医疗器械",
    "goods":[
      {
        "id":"31",
        "name":"心脑血管",
        "arr":[
          {
            "id":"32",
            "name":"心绞痛",
            "img":"http://static.360hwj.com/group1/M00/01/F8/J2zAA1lwYXiAftXyAAFElVpO-LQ620.jpg"
          },
          {
            "id":"33",
            "name":"血压异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          },
          {
            "id":"34",
            "name":"血脂异常",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwGmmAGxluAABMsdGxEZk146.jpg"
          },
          {
            "id":"35",
            "name":"脑血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwFbGAe6jmAABxOpNd5dU469.jpg"
          },
          {
            "id":"36",
            "name":"心血管疾病",
            "img":"http://static.360hwj.com/group1/M00/01/F7/J2zAA1lwE3SARwMNAACfgB7zY5c787.jpg"
          }
        ]
      }
    ]
  },
  {
    "id":"37",
    "name":"家居日用",
    "goods":[]
  },
  {
    "id":"38",
    "name":"保健食品",
    "goods":[]
  },
  {
    "id":"39",
    "name":"成人用品",
    "goods":[]
  },
  {
    "id":"40",
    "name":"滋补品",
    "goods":[]
  },
  {
    "id":"41",
    "name":"眼镜",
    "goods":[]
  },
  {
    "id":"42",
    "name":"中药饮片",
    "goods":[]
  }
]
}

