export default {
  "data":[
  {
    "id":1,
    "name":"内科",
    "arr":[
      {
        "id":2,
        "name":"呼吸内科",
        "arr":[
          {
            "id":3,
            "name":"哮喘",
            "value":"哮喘"
          },
          {
            "id":4,
            "name":"支气管炎",
            "value":"支气管炎"
          },
          {
            "id":5,
            "name":"流行性感冒",
            "value":"流行性感冒"
          },
          {
            "id":6,
            "name":"感冒",
            "value":"感冒"
          },
          {
            "id":7,
            "name":"肺炎",
            "value":"肺炎"
          },
          {
            "id":8,
            "name":"慢性支气管疾病",
            "value":"慢性支气管疾病"
          }
        ]
      },
      {
        "id":9,
        "name":"肾内科",
        "arr":[
          {
            "id":10,
            "name":"肾病",
            "value":"肾病"
          },
          {
            "id":11,
            "name":"肾炎",
            "value":"肾炎"
          },
          {
            "id":12,
            "name":"肾盂肾炎",
            "value":"肾盂肾炎"
          },
          {
            "id":13,
            "name":"肾功能衰竭",
            "value":"肾功能衰竭"
          },
          {
            "id":14,
            "name":"狼疮性肾炎",
            "value":"狼疮性肾炎"
          },
          {
            "id":15,
            "name":"尿毒症",
            "value":"尿毒症"
          }
        ]
      },
      {
        "id":16,
        "name":"消化内科",
        "arr":[
          {
            "id":17,
            "name":"胃炎",
            "value":"胃炎"
          },
          {
            "id":18,
            "name":"胃溃疡",
            "value":"胃溃疡"
          },
          {
            "id":19,
            "name":"肠胃炎",
            "value":"肠胃炎"
          },
          {
            "id":20,
            "name":"胃下垂",
            "value":"胃下垂"
          },
          {
            "id":21,
            "name":"胃十二指肠溃疡",
            "value":"胃十二指肠溃疡"
          },
          {
            "id":22,
            "name":"结肠炎",
            "value":"结肠炎"
          }
        ]
      },
      {
        "id":23,
        "name":"神经内科",
        "arr":[
          {
            "id":24,
            "name":"失眠",
            "value":"失眠"
          },
          {
            "id":25,
            "name":"头痛",
            "value":"头痛"
          },
          {
            "id":26,
            "name":"面瘫",
            "value":"面瘫"
          },
          {
            "id":27,
            "name":"内耳眩晕",
            "value":"内耳眩晕"
          },
          {
            "id":28,
            "name":"神经衰弱",
            "value":"神经衰弱"
          },
          {
            "id":29,
            "name":"癫痫",
            "value":"癫痫"
          }
        ]
      }
    ]
  },
  {
    "id":30,
    "name":"外科",
    "arr":[
      {
        "id":31,
        "name":"普外科",
        "arr":[
          {
            "id":32,
            "name":"阑尾炎",
            "value":"阑尾炎"
          },
          {
            "id":33,
            "name":"胆囊炎",
            "value":"胆囊炎"
          },
          {
            "id":34,
            "name":"胆结石",
            "value":"胆结石"
          },
          {
            "id":35,
            "name":"痔疮",
            "value":"痔疮"
          },
          {
            "id":36,
            "name":"肛裂",
            "value":"肛裂"
          },
          {
            "id":37,
            "name":"肛瘘",
            "value":"肛瘘"
          }
        ]
      },
      {
        "id":38,
        "name":"泌尿外科",
        "arr":[
          {
            "id":39,
            "name":"阑尾炎",
            "value":"阑尾炎"
          },
          {
            "id":40,
            "name":"尿路感染",
            "value":"尿路感染"
          },
          {
            "id":41,
            "name":"胆结石",
            "value":"胆结石"
          },
          {
            "id":42,
            "name":"痔疮",
            "value":"痔疮"
          },
          {
            "id":43,
            "name":"肛裂",
            "value":"肛裂"
          },
          {
            "id":44,
            "name":"肛瘘",
            "value":"肛瘘"
          }
        ]
      }
    ]
  }
]
}
